#! /bin/sh

cd $(dirname "$0") || exit 1

while read -r package ; do
    ./xbps-src pkg "${package}" -E
done < ./etc/packages

BRANCH=$(git rev-parse --abbrev-ref HEAD)
xbps-rindex -r "$PWD/hostdir/binpkgs/$BRANCH"
xbps-rindex -r "$PWD/hostdir/binpkgs/$BRANCH/nonfree"

